server:
  port: 8083
spring:
  application:
    name: cloud-docker-kafka
  cloud:
     instance-count: 1
     instance-index: 0
     stream:
        kafka:
          binder:
            brokers: 192.168.229.128:9092
            zk-nodes: 192.168.229.128:2181
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 1
        bindings:
          output:
            destination: mytopic
            content-type: text/plain
            producer:
              partitionCount: 1
#          input:
#            destination: mytopic
#            group: s1
#            consumer:
#              autoCommitOffset: false
#              concurrency: 1
#              partitioned: false