spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000

