eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9084
spring:
  application:
    name: cloud-zuul
  zipkin:
    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1
zuul:
  routes:
    api-a:
      path: /api-tag/**
      serviceId: tag-client
    api-b:
      path: /api-b/**
      serviceId: cloud-service1